// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package users

import (
	"time"
)

type User struct {
	ID         int32     `db:"id" json:"id"`
	Email      string    `db:"email" json:"email"`
	FirstName  string    `db:"first_name" json:"firstName"`
	LastName   string    `db:"last_name" json:"lastName"`
	Password   string    `db:"password" json:"password"`
	UserActive int32     `db:"user_active" json:"userActive"`
	CreatedAt  time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt  time.Time `db:"updated_at" json:"updatedAt"`
}
